### ISSUE TITLE
Question about data in the stat

### ISSUE THREAD

**Issue by c933103** [pcaisse/language-map-us#14]
- Is there no data for other United States territories, like Guam, Northern Mariana, USVI, or American Samoa available?
- I see data break down for Cantonese and Mandarin in the table but is there no data for other Chinese variants like Hakka or Szeyap and such? Is the parent category "Chinese" a sum of these data or?
- Is there no data for English? While I guess it will not have much meaning as I assume all states will have more than 10% people being able to speak English,I still think it would be nice if that's added to the site

**Comment by pcaisse** [comment]
Thanks for your interest in the project!

I believe your questions are answered in threads in a Reddit post I made a while back about the Language Map [here](https://www.reddit.com/r/linguistics/comments/b7uhbb/language_map_of_the_united_states/ejuifh2?utm_source=share&utm_medium=web2x) and [here](https://www.reddit.com/r/linguistics/comments/b7uhbb/language_map_of_the_united_states/ejujy9j?utm_source=share&utm_medium=web2x).

You may also be interested in the FAQ (link is in the top right corner of http://languagemap.us) which covers some of the same questions and answers.
