### ISSUE TITLE
Improve popover styling

### ISSUE THREAD

**Issue by alexelash** [pcaisse/language-map-us#3]
<img width="409" alt="screen shot 2018-12-12 at 9 23 12 am" src="https://user-images.githubusercontent.com/5672295/49875695-a7dba180-fdef-11e8-80b1-891dfb6771d3.png">

A couple of things we could do here:
- Use comma separation for thousands
- Consider making the percentage more prominent
- Consider making the state/puma name more prominent

**Comment by pcaisse** [comment]
This link should provide a starting point for how to style the tooltip: https://gis.stackexchange.com/questions/212820/overriding-leaflet-tooltip-style

One thing I've noticed is that, especially with PUMAs, the name is often so long it can make the tooltip very wide to the extent that it's hard to read on mobile. We might want to give the tooltip a max width or perhaps ellipsize the text or in some other way make it easier to read.

As you mentioned before, we should probably revisit the labels. Something like: `Speakers: 205457 (7.088899%)` might be sufficient, or maybe even just `205457 (7.088899%)`.

**Comment by pcaisse** [comment]
I tried to address these issues with the tooltip by doing the following:
* Wrapping tooltip text and setting a min width for the tooltip
* Changing "Number of speakers" to "Speakers"
* Making the state/PUMA name bold
* Displaying a localized string for speaker counts and percentages (as well as legend percentages) (see also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString). This will display counts/percentages with appropriate delimiters based on the locale. It will also display an appropriate level of precision based on which range it falls into (the fewer the speakers, the more precision after the decimal).

This went into release 1.9.0 which has been deployed.

**Comment by pcaisse** [comment]
Another change made to the popover is that it now follows the mouse so it's always visible to the user regardless of where they mouseover/tap.

**Comment by pcaisse** [comment]
This will likely need a few more minor tweaks (there's flicker when you cross over PUMA outlines with the cursor) but that will go in a separate catch-all issue (see https://github.com/pcaisse/language-map-us/issues/5).
